font_size 16.0
background_opacity 0.98

cursor_shape beam
cursor_trail 1

window_margin_width 22

confirm_os_window_close 0



# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="Hasklug Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS